version: '3.8'

services:
    app_laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: app:latest
        container_name: frankenphp_app
        restart: unless-stopped
        volumes:
            - ./public/build:/app/public/build
            - laravel_storage:/app/storage
            - laravel_cache:/app/bootstrap/cache
        ports:
            - "9001:80"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: frankenphp_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laraveluser
            POSTGRES_PASSWORD: secret
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    laravel_storage:
    laravel_cache:
    postgres_data:
